<script setup>
import { reactive, ref, watch } from 'vue'
import { useAuth } from '@/stores/auth'
import { useOverlayLock } from '@/composables/useOverlayLock'
import http from '@/http'
const props=defineProps({modelValue:Boolean,mode:{type:String,default:'create'},user:Object,role:{type:String,default:'USER'}})
const emit=defineEmits(['update:modelValue','saved'])
const auth=useAuth(),visible=ref(false),busy=ref(false),reading=ref(false),readFailed=ref(false),error=ref(''),uncertain=ref(false)
const form=reactive({username:'',password:'',displayName:'',role:'USER',permissions:[],campus:'',bio:'',reason:'',version:0})
const scopes={ALL:'超级管理员（全部权限）',USERS:'账号管理',ITEMS:'物品审核',CATEGORIES:'分类维护',EXCHANGES:'交换管理',HISTORY:'履历核验',REPORTS:'举报处理',COMMUNITY:'校园动态',OPERATIONS:'运营统计'}
let sequence=0
useOverlayLock(visible)
watch(()=>props.modelValue,async value=>{visible.value=value;const run=++sequence;if(!value){form.password='';return}error.value='';readFailed.value=false;uncertain.value=false;Object.assign(form,{username:'',password:'',displayName:'',role:props.role,permissions:[],campus:'',bio:'',reason:'',version:0});if(props.mode!=='create'){reading.value=true;try{const {data}=await http.get(`/api/admin/users/${props.user.id}/profile`,{silent:true});if(run===sequence)Object.assign(form,data,{password:'',reason:''})}catch(e){if(run===sequence){readFailed.value=true;error.value=e.response?.data?.msg||'账号资料读取失败，请关闭后重试'}}finally{if(run===sequence)reading.value=false}}})
function close(){if(!busy.value)emit('update:modelValue',false)}
async function save(){if(busy.value||reading.value||readFailed.value||uncertain.value)return;error.value='';if(!form.reason.trim()){error.value='请填写操作原因';return}if(props.mode!=='reset'&&!form.displayName.trim()){error.value='请填写显示名称';return}if(props.mode!=='edit'&&(form.password.length<12||form.password.length>64||new TextEncoder().encode(form.password).length>72)){error.value='密码需为 12–64 个字符';return}if(props.mode==='create'&&!/^[A-Za-z0-9_.-]{3,64}$/.test(form.username)){error.value='用户名需为 3–64 位字母、数字、_ . -';return}if(props.mode==='create'&&form.role==='ADMIN'&&!form.permissions.length){error.value='请为管理员选择权限';return}
 busy.value=true;try{const reason=form.reason.trim();if(props.mode==='create')await http.post('/api/admin/users',{username:form.username,password:form.password,displayName:form.displayName.trim(),role:form.role,permissions:form.role==='ADMIN'?form.permissions:[],reason},{silent:true});else if(props.mode==='edit')await http.put(`/api/admin/users/${props.user.id}/profile`,{version:form.version,displayName:form.displayName.trim(),campus:form.campus,bio:form.bio,reason},{silent:true});else await http.post(`/api/admin/users/${props.user.id}/password`,{version:form.version,password:form.password,reason},{silent:true});form.password='';emit('saved');emit('update:modelValue',false)}catch(e){error.value=e.response?.data?.msg||'未收到操作结果，请关闭窗口并刷新账号列表确认。';uncertain.value=!e.response||e.response.status===409}finally{busy.value=false}}
</script>
<template><el-dialog :model-value="modelValue" :title="mode==='create'?'新增账号':mode==='edit'?'编辑账号资料':'重置账号密码'" width="min(580px,94vw)" :lock-scroll="false" :close-on-click-modal="!busy" :close-on-press-escape="!busy" :show-close="!busy" @update:model-value="close"><el-form v-loading="reading" label-position="top" @submit.prevent="save"><fieldset :disabled="busy||reading||readFailed||uncertain" class="account-fields"><p v-if="mode!=='create'">@{{form.username}}</p><el-form-item v-if="mode==='create'" label="用户名"><el-input v-model="form.username" aria-label="新增用户名" maxlength="64" autocomplete="off" placeholder="字母、数字、_ . -"/></el-form-item><el-form-item v-if="mode!=='reset'" label="显示名称"><el-input v-model="form.displayName" aria-label="账号显示名称" maxlength="64"/></el-form-item><el-form-item v-if="mode==='create'" label="账号类型"><el-radio-group v-model="form.role"><el-radio value="USER">普通用户</el-radio><el-radio value="ADMIN" :disabled="!auth.user?.permissions?.includes('ALL')">管理员</el-radio></el-radio-group></el-form-item><el-form-item v-if="mode==='create'&&form.role==='ADMIN'" label="管理权限"><el-checkbox-group v-model="form.permissions" class="scopes"><el-checkbox v-for="(label,key) in scopes" :key="key" :value="key">{{label}}</el-checkbox></el-checkbox-group></el-form-item><template v-if="mode==='edit'"><el-form-item label="所在校区"><el-input v-model="form.campus" aria-label="账号所在校区" maxlength="100"/></el-form-item><el-form-item label="个人介绍"><el-input v-model="form.bio" aria-label="账号个人介绍" type="textarea" :rows="3" maxlength="300" show-word-limit/></el-form-item></template><el-form-item v-if="mode!=='edit'" :label="mode==='create'?'初始密码':'新密码'"><el-input v-model="form.password" aria-label="账号新密码" type="password" show-password maxlength="64" autocomplete="new-password" placeholder="12–64 个字符"/></el-form-item><p v-if="mode==='reset'" class="hint">重置后，该账号需使用新密码重新登录。</p><el-form-item label="操作原因"><el-input v-model="form.reason" aria-label="账号操作原因" type="textarea" :rows="2" maxlength="500" show-word-limit placeholder="例如：新增校园运营人员"/></el-form-item></fieldset><el-alert v-if="error" :title="error" type="error" :closable="false"/><div class="actions"><el-button :disabled="busy" @click="close">取消</el-button><el-button type="primary" native-type="submit" :loading="busy" :disabled="reading||readFailed||uncertain">{{mode==='create'?'创建账号':'保存'}}</el-button></div></el-form></el-dialog></template>
<style scoped>.account-fields{border:0;padding:0;margin:0;min-width:0}.scopes{display:grid;grid-template-columns:1fr 1fr;max-width:100%}.actions{display:flex;justify-content:flex-end;gap:12px;margin-top:24px}.hint{color:var(--cl-muted);font-size:13px}@media(max-width:560px){.scopes{grid-template-columns:1fr}}</style>
