const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const {ref,reactive,nextTick}=require('vue')
const script=fs.readFileSync(path.join(__dirname,'../src/components/ItemGalleryUpload.vue'),'utf8').match(/<script setup>([\s\S]*?)<\/script>/)[1].replace(/^import .*$/gm,'')
function harness(){let token='a',dispose;const choices=[],requests=[],events=[];const props=reactive({modelValue:[],disabled:false});const emit=(name,value)=>{events.push([name,value]);if(name==='update:modelValue')props.modelValue=value};const http={upload:()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});const r={resolve,reject,aborted:false};promise.abort=()=>r.aborted=true;requests.push(r);return promise}};const uni={getStorageSync:()=>token,chooseImage:o=>choices.push(o)};const args={ref,nextTick,onBeforeUnmount:fn=>dispose=fn,defineProps:()=>props,defineEmits:()=>emit,http,uni,TOKEN_KEY:'token',imageUrl:v=>v,isAbortError:e=>e.code==='ABORTED'};const app=new Function(...Object.keys(args),script+';return {choose,upload,cancel,cover,remove,pending,busy,error};')(...Object.values(args));return {app,props,choices,requests,events,setToken:t=>token=t,dispose:()=>dispose()}}
const settle=async()=>{await Promise.resolve();await nextTick();await Promise.resolve()}
test('gallery retains successful images, retries only remaining failures and selects cover',async()=>{const h=harness();h.app.choose();h.choices[0].success({tempFilePaths:['a','b']});h.requests[0].resolve({url:'/uploads/a.png'});await settle();h.requests[1].reject(new Error('failed'));await settle();assert.deepEqual([...h.props.modelValue],['/uploads/a.png']);assert.deepEqual([...h.app.pending.value],['b']);const retry=h.app.upload();h.requests[2].resolve({url:'/uploads/b.png'});await retry;h.app.cover(1);assert.deepEqual([...h.props.modelValue],['/uploads/b.png','/uploads/a.png']);h.app.remove(1);assert.equal(h.props.modelValue.length,1)})
test('native picker callback from an old session cannot upload as a new user',()=>{const h=harness();h.app.choose();h.setToken('b');h.choices[0].success({tempFilePaths:['old']});assert.equal(h.requests.length,0)})
for(const end of ['switch','unmount'])test(`late upload after ${end} cannot change photos`,async()=>{const h=harness();h.app.pending.value=['a'];const job=h.app.upload();if(end==='switch')h.setToken('b');else h.dispose();h.requests[0].resolve({url:'/uploads/old.png'});await job;assert.equal(h.props.modelValue.length,0);if(end==='unmount')assert.equal(h.requests[0].aborted,true)})
test('late cancelled upload cannot overwrite a retry',async()=>{const h=harness();h.app.pending.value=['a'];const old=h.app.upload();h.app.cancel();const retry=h.app.upload();h.requests[0].resolve({url:'/uploads/old.png'});await old;assert.equal(h.app.busy.value,true);h.requests[1].resolve({url:'/uploads/new.png'});await retry;assert.deepEqual([...h.props.modelValue],['/uploads/new.png'])})
test('nine photos limit blocks opening native picker',()=>{const h=harness();h.props.modelValue=Array.from({length:9},(_,i)=>'/uploads/'+i);h.app.choose();assert.equal(h.choices.length,0)})
