<script setup>
import {ref} from 'vue'
import LoopSheet from '../../components/LoopSheet.vue'
import {useTheme,palettes} from '../../composables/useTheme'
const appearanceOpen=ref(false)
const {theme,palette,style,setAppearance,toggleTheme,reducedMotion,toggleMotion}=useTheme()
import {onShow,onHide,onUnload} from '@dcloudio/uni-app'
import LoopLayout from '../../components/LoopLayout.vue'
import LoopButton from '../../components/LoopButton.vue'
import LoopIcon from '../../components/LoopIcon.vue'
import LoopSkeleton from '../../components/LoopSkeleton.vue'
import http,{TOKEN_KEY,USER_KEY,imageUrl,clearSession} from '../../common/http'
import {showAppModal} from '../../common/modal'
const user=ref(null),loading=ref(false),error=ref(''),counts=ref({})
let sequence=0
const go=page=>page==='appearance'?appearanceOpen.value=true:uni.navigateTo({url:`/pages/${page}/${page}`})
const home=()=>uni.navigateTo({url:`/pages/member/member?id=${user.value.id}`})
const login=()=>uni.navigateTo({url:'/pages/login/login?redirect=profile'})
const entries=[{page:'my-items',icon:'box',title:'我的物品',hint:'管理发布、上架与交换状态'},{page:'exchanges',icon:'exchange',title:'我的交换',hint:'查看订单与交接进度'},{page:'demands',icon:'target',title:'我的需求',hint:'管理想换到的好物'},{page:'notifications',icon:'bell',title:'消息通知',hint:'交换邀请、评论和审核消息'},{page:'favorites',icon:'heart',title:'我的收藏',hint:'看看收藏的好物'},{page:'profile-settings',icon:'user',title:'个人资料',hint:'修改头像、简介和账号资料'},{page:'appearance',icon:'sun',title:'主题与外观',hint:'配色、风格和深浅模式'},{page:'governance',icon:'check',title:'举报与争议',hint:'查看处理进度'}]
async function load(){const id=++sequence,token=uni.getStorageSync(TOKEN_KEY);user.value=null;counts.value={};error.value='';loading.value=!!token;if(!token)return;try{const u=await http.get('/api/auth/me',{}, {silent:true});if(id!==sequence||token!==uni.getStorageSync(TOKEN_KEY))return;user.value=u;uni.setStorageSync(USER_KEY,u);const c=await http.get('/api/members/'+u.id,{}, {silent:true});if(id===sequence&&token===uni.getStorageSync(TOKEN_KEY))counts.value=c}catch(e){if(id===sequence)error.value=e.message}finally{if(id===sequence)loading.value=false}}
async function logout(){const token=uni.getStorageSync(TOKEN_KEY);const result=await showAppModal({title:'退出登录',content:'确认退出当前账号？'});if(!result.confirm||token!==uni.getStorageSync(TOKEN_KEY))return;try{await http.post('/api/auth/logout',{}, {silent:true})}catch{}if(token===uni.getStorageSync(TOKEN_KEY)){clearSession();load()}}
onShow(load);onHide(()=>sequence++);onUnload(()=>sequence++)
</script>
<template><LoopLayout active-tab="profile"><view class="cl-page-heading"><text class="cl-title">我的</text><text class="cl-subtitle">发布好物，认识同学，随时查看交换进度。</text></view><LoopSkeleton v-if="loading"/><view v-else-if="!user" class="cl-panel cl-empty"><LoopIcon name="user" tone="primary" :size="40"/><text>{{error||'登录后开启你的校园小铺'}}</text><LoopButton class="cl-btn cl-btn--primary" @click="login">登录</LoopButton><LoopButton v-if="error" class="cl-btn" @click="load">重试</LoopButton></view><template v-else><view class="cl-panel member-banner"><LoopButton class="identity" aria-label="查看我的个人主页" @click="home"><image v-if="user.avatarUrl" :src="imageUrl(user.avatarUrl)" mode="aspectFill"/><text v-else class="avatar">{{user.displayName?.slice(0,1)}}</text><view><text class="cl-title">{{user.displayName}}</text><text class="cl-hint">{{user.campus||'校园交换同学'}} · 查看我的主页 ›</text></view></LoopButton><LoopButton class="cl-btn" @click="logout">退出登录</LoopButton><view class="member-stats"><text>{{counts.itemCount??'—'}} 件在架物品</text><text>{{counts.exchangeCount??'—'}} 次完成交换</text></view></view><view class="hub-grid"><LoopButton v-for="(entry,index) in entries" :key="entry.page" class="cl-panel hub-entry" :class="{featured:index<2}" @click="go(entry.page)"><view class="entry-icon"><LoopIcon :name="entry.icon" tone="primary" :size="28"/></view><view><text class="entry-title">{{entry.title}}</text><text class="cl-hint">{{entry.hint}}</text></view><LoopIcon name="arrow" :size="18"/></LoopButton></view></template><LoopSheet v-model="appearanceOpen" title="主题与外观"><view class="cl-stack"><text class="cl-field-title">主题配色</text><LoopButton v-for="p in palettes" :key="p.id" class="cl-btn" :aria-pressed="palette===p.id" :style="{borderColor:theme==='dark'?p.dark:p.color,color:theme==='dark'?p.dark:p.color}" @click="setAppearance(p.id,style)">{{palette===p.id?'✓ ':''}}{{p.name}}</LoopButton><text class="cl-field-title">界面风格</text><LoopButton class="cl-btn" @click="setAppearance(palette,'soft')">{{style==='soft'?'✓ ':''}}柔和圆角</LoopButton><LoopButton class="cl-btn" @click="setAppearance(palette,'simple')">{{style==='simple'?'✓ ':''}}简洁清爽</LoopButton><LoopButton class="cl-btn" @click="toggleTheme">{{theme==='dark'?'深色模式 · 切换浅色':'浅色模式 · 切换深色'}}</LoopButton><LoopButton class="cl-btn" @click="toggleMotion">{{reducedMotion?'✓ ':''}}减少动态效果</LoopButton></view></LoopSheet></LoopLayout></template>
<style scoped>
.member-banner{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap;background:linear-gradient(115deg,var(--cl-primary-soft),var(--cl-surface),var(--cl-blue-soft))}.identity{display:flex;align-items:center;gap:20px;text-align:left;background:transparent;color:var(--cl-text);padding:0}.identity image,.avatar{width:80px;height:80px;border-radius:24px;flex:none}.avatar{display:flex;align-items:center;justify-content:center;background:var(--cl-primary-soft);color:var(--cl-primary);font-size:36px;font-weight:700}.identity>view{display:flex;flex-direction:column;gap:12px}.member-stats{width:100%;display:flex;gap:32px;border-top:1px solid var(--cl-border);padding-top:20px;color:var(--cl-muted);font-size:14px}.hub-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:24px}.hub-entry{display:flex;align-items:center;gap:18px;text-align:left;color:var(--cl-text)}.hub-entry>view:nth-child(2){flex:1;display:flex;flex-direction:column;gap:8px;min-width:0}.entry-icon{width:56px;height:56px;border-radius:18px;background:var(--cl-primary-soft);display:flex;align-items:center;justify-content:center;flex:none}.entry-title{font-size:20px;font-weight:700}.featured{border-color:var(--cl-primary);background:linear-gradient(120deg,var(--cl-primary-soft),var(--cl-surface))}.featured .entry-title{font-size:24px}@media(max-width:600px){.hub-grid{grid-template-columns:1fr}.member-banner,.hub-entry{padding:20px}.identity{gap:12px}.identity image,.avatar{width:60px;height:60px}.identity .cl-title{font-size:24px}.member-stats{gap:20px}.entry-title,.featured .entry-title{font-size:19px}}
</style>
