<script setup>
import AssistantReview from "@/components/AssistantReview.vue"
import { ref, reactive, onMounted, onBeforeUnmount } from 'vue'
import { useOverlayLock } from '@/composables/useOverlayLock'
import http from '@/http'
import { ElMessageBox } from 'element-plus'
const filters=reactive({keyword:'',reported:false,page:1,size:15}),rows=ref([]),total=ref(0),loading=ref(false),error=ref(''),notice=ref('')
const visible=ref(false),detail=ref(null),reports=ref([]),audits=ref([]),replies=ref([]),replyPage=ref(1),replyTotal=ref(0),detailBusy=ref(false),detailError=ref(''),reason=ref(''),action=ref('HIDE'),saving=ref(false),uncertain=ref(false)
let listSequence=0,detailSequence=0
useOverlayLock(visible)
const message=e=>e.response?.data?.msg||'暂时无法连接服务，请稍后重试。'
const time=v=>v?new Date(/(?:Z|[+-]\d{2}:\d{2})$/.test(v)?v:v+'Z').toLocaleString('zh-CN',{hour12:false}):''
const actionName=v=>({HIDE:'隐藏动态',RESTORE:'恢复展示',DISMISS_REPORTS:'举报不成立',WITHDRAW:'作者删除',REPLY_DELETED:'删除回复'})[v]||v
async function load(){const run=++listSequence;loading.value=true;error.value='';try{const {data}=await http.get('/api/admin/community/posts',{params:filters,silent:true});if(run===listSequence){rows.value=data.records;total.value=data.total;if(!rows.value.length&&filters.page>1){filters.page--;return load()}}}catch(e){if(run===listSequence)error.value=message(e)}finally{if(run===listSequence)loading.value=false}}
function search(){filters.page=1;load()}
async function open(row){visible.value=true;detail.value=row;reason.value='';uncertain.value=false;replyPage.value=1;action.value=row.status==='HIDDEN'?'RESTORE':'HIDE';await readDetail()}
async function readDetail(){if(!detail.value)return;const run=++detailSequence,id=detail.value.id;detailBusy.value=true;detailError.value='';reports.value=[];audits.value=[];replies.value=[];try{const results=await Promise.all([http.get(`/api/admin/community/posts/${id}`,{silent:true}),http.get(`/api/admin/community/posts/${id}/reports`,{silent:true}),http.get(`/api/admin/community/posts/${id}/audits`,{silent:true}),http.get(`/api/admin/community/posts/${id}/replies`,{params:{page:replyPage.value},silent:true})]);if(run===detailSequence&&visible.value){detail.value=results[0].data;if((action.value==='HIDE'&&detail.value.status==='HIDDEN')||(action.value==='RESTORE'&&detail.value.status==='PUBLISHED'))action.value=detail.value.status==='HIDDEN'?'RESTORE':'HIDE';reports.value=results[1].data;audits.value=results[2].data;replies.value=results[3].data.records;replyTotal.value=results[3].data.total;uncertain.value=false}}catch(e){if(run===detailSequence)detailError.value=message(e)}finally{if(run===detailSequence)detailBusy.value=false}}
async function save(){if(saving.value||uncertain.value||detailBusy.value)return;if(!reason.value.trim()){detailError.value='请填写处理原因';return}saving.value=true;detailError.value='';try{await http.post(`/api/admin/community/posts/${detail.value.id}/moderate`,{version:detail.value.version,action:action.value,reason:reason.value.trim()},{silent:true});notice.value='处理已保存。';reason.value='';await Promise.all([load(),readDetail()])}catch(e){detailError.value=message(e);uncertain.value=!e.response||e.response.status===409}finally{saving.value=false}}
async function removeReply(row){if(saving.value)return;try{await ElMessageBox.confirm('删除这条回复后，将不再公开展示。','删除回复',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'})}catch{return}saving.value=true;try{await http.delete(`/api/community/posts/${detail.value.id}/replies/${row.id}`,{silent:true});await readDetail()}catch(e){detailError.value=message(e)}finally{saving.value=false}}
function close(){if(saving.value)return;visible.value=false;detailSequence++}
onMounted(load);onBeforeUnmount(()=>{listSequence++;detailSequence++})
</script>
<template><div class="page-heading"><div><span class="eyebrow">CAMPUS COMMUNITY</span><h1>校园动态</h1><p>查看同学分享，处理举报与不合适的内容。</p></div><span class="count-pill">共 {{total}} 条动态</span></div><el-alert v-if="notice" :title="notice" type="success" class="notice" show-icon/><section class="panel"><form class="filter-bar" @submit.prevent="search"><el-input v-model="filters.keyword" aria-label="搜索校园动态" placeholder="动态内容或发布者" clearable/><el-checkbox v-model="filters.reported" @change="search">仅看待处理举报</el-checkbox><el-button type="primary" native-type="submit" :loading="loading">搜索</el-button><el-button @click="filters.keyword='';filters.reported=false;search()">重置</el-button></form><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-table v-loading="loading" :data="rows" row-key="id"><el-table-column label="动态" min-width="300"><template #default="{row}"><strong>{{row.authorName}}</strong><p class="post-summary">{{row.body}}</p><small v-if="row.itemTitle">关联物品：{{row.itemTitle}}</small></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='HIDDEN'?'warning':'success'">{{row.status==='HIDDEN'?'已隐藏':'展示中'}}</el-tag></template></el-table-column><el-table-column label="互动" width="130"><template #default="{row}">{{row.likes}} 赞 · {{row.replies}} 回复</template></el-table-column><el-table-column label="待处理举报" width="110"><template #default="{row}"><el-tag v-if="row.reports" type="danger">{{row.reports}}</el-tag><span v-else>—</span></template></el-table-column><el-table-column label="发布时间" min-width="175"><template #default="{row}">{{time(row.createdAt)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button type="primary" link @click="open(row)">查看处理</el-button></template></el-table-column><template #empty><el-empty description="暂无符合条件的动态" :image-size="70"/></template></el-table><div class="pagination-row"><span></span><el-pagination v-model:current-page="filters.page" :page-size="filters.size" :total="total" layout="prev, pager, next" :pager-count="5" background @current-change="load"/></div></section>
<el-drawer :model-value="visible" title="动态详情与处理" size="min(720px,100vw)" :lock-scroll="false" :close-on-click-modal="!saving" :close-on-press-escape="!saving" :show-close="!saving" @update:model-value="close"><div v-if="detail" v-loading="detailBusy" class="detail-stack"><AssistantReview :key="detail.id" :endpoint="`/api/admin/community/posts/${detail.id}/assist-review`"/><header><h2>{{detail.authorName}}</h2><small>{{time(detail.createdAt)}}</small></header><p class="post-body">{{detail.body}}</p><img v-if="detail.imageUrl" :src="detail.imageUrl" class="post-image" alt="动态配图"/><p v-if="detail.itemTitle">关联物品：{{detail.itemTitle}}</p><section><h3>举报记录</h3><p v-if="!reports.length" class="muted">暂无举报</p><article v-for="report in reports" :key="report.id" class="detail-card"><strong>{{report.reporterName}} · {{report.status==='OPEN'?'待处理':'已处理'}}</strong><p>{{report.reason}}</p><small>{{time(report.createdAt)}}</small></article></section><el-form label-position="top" @submit.prevent="save"><el-form-item label="处理方式"><el-radio-group v-model="action" :disabled="saving||uncertain"><el-radio value="HIDE" :disabled="detail.status==='HIDDEN'">隐藏动态</el-radio><el-radio value="RESTORE" :disabled="detail.status!=='HIDDEN'">恢复展示</el-radio><el-radio value="DISMISS_REPORTS">举报不成立</el-radio></el-radio-group></el-form-item><el-form-item label="处理原因"><el-input v-model="reason" aria-label="动态处理原因" type="textarea" :rows="3" maxlength="500" :disabled="saving||uncertain" show-word-limit/></el-form-item><el-alert v-if="detailError" :title="detailError" type="error" :closable="false"/><div class="actions"><el-button :disabled="saving" @click="readDetail">刷新详情</el-button><el-button type="primary" native-type="submit" :loading="saving" :disabled="uncertain||detailBusy">保存处理</el-button></div></el-form><section><h3>回复 · {{replyTotal}}</h3><p v-if="!replies.length" class="muted">暂无回复</p><article v-for="reply in replies" :key="reply.id" class="detail-card"><strong>{{reply.authorName}}</strong><p>{{reply.body}}</p><small>{{time(reply.createdAt)}}</small><el-button type="danger" link :disabled="saving" @click="removeReply(reply)">删除回复</el-button></article><el-pagination v-if="replyTotal>20" v-model:current-page="replyPage" :page-size="20" :total="replyTotal" layout="prev, pager, next" @current-change="readDetail"/></section><section><h3>处理记录</h3><p v-if="!audits.length" class="muted">暂无记录</p><article v-for="audit in audits" :key="audit.id" class="detail-card"><strong>{{actionName(audit.action)}} · {{audit.actorName}}</strong><p>{{audit.reason}}</p><small>{{time(audit.createdAt)}}</small></article></section></div></el-drawer></template>
<style scoped>.notice{margin-bottom:20px}.post-summary{white-space:pre-wrap;overflow-wrap:anywhere;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;margin:8px 0}.post-body,.detail-card p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8}.detail-stack{display:flex;flex-direction:column;gap:20px}.detail-stack h2{margin-bottom:8px}.detail-stack small,.muted{color:var(--cl-muted)}.post-image{max-width:100%;max-height:340px;object-fit:contain;border-radius:16px;align-self:flex-start}.detail-card{padding:16px;border:1px solid var(--cl-border);border-radius:14px;margin-bottom:12px}.detail-card .el-button{margin-left:16px}.actions{display:flex;justify-content:flex-end;gap:12px;margin-top:16px}</style>
