<script setup>
import {ref} from 'vue'
import {onLoad,onShow,onHide,onUnload} from '@dcloudio/uni-app'
import LoopLayout from '../../components/LoopLayout.vue'
import LoopButton from '../../components/LoopButton.vue'
import LoopIcon from '../../components/LoopIcon.vue'
import LoopSkeleton from '../../components/LoopSkeleton.vue'
import ItemCard from '../../components/ItemCard.vue'
import http,{imageUrl} from '../../common/http'
const member=ref(null),items=ref([]),loading=ref(true),error=ref(''),page=ref(1),total=ref(0)
let memberId=0,sequence=0
async function load(next=page.value){const current=++sequence;loading.value=true;error.value='';try{const [profile,list]=await Promise.all([http.get(`/api/members/${memberId}`,{}, {silent:true}),http.get(`/api/members/${memberId}/items`,{page:next,size:12},{silent:true})]);if(current!==sequence)return;member.value=profile;items.value=list.records;page.value=list.page;total.value=list.total}catch(e){if(current===sequence){member.value=null;items.value=[];error.value=e.message}}finally{if(current===sequence)loading.value=false}}
onLoad(options=>{memberId=Number(options.id)||0});onShow(()=>load());onHide(()=>sequence++);onUnload(()=>sequence++)
</script>
<template><LoopLayout><LoopSkeleton v-if="loading&&!member"/><view v-if="error" class="cl-panel cl-empty" role="alert"><text>{{error}}</text><LoopButton class="cl-btn" @click="load()">重试</LoopButton></view><template v-if="member"><view class="member-cover"><image v-if="member.coverUrl" :src="imageUrl(member.coverUrl)" mode="aspectFill" style="width:100%;height:100%"/><view v-else class="cover-pattern"><LoopIcon name="exchange" :size="100" tone="primary"/><text>校园好物 · 继续有用</text></view></view><view class="cl-panel public-profile"><image v-if="member.avatarUrl" class="member-avatar" :src="imageUrl(member.avatarUrl)" mode="aspectFill"/><text v-else class="member-avatar fallback">{{member.displayName?.slice(0,1)}}</text><view class="public-copy"><text class="cl-title">{{member.displayName}}的主页</text><text class="cl-hint"><LoopIcon name="home" :size="16"/> {{member.campus||'校园交换同学'}}</text><text class="member-bio">{{member.bio||'欢迎来看看我的好物，一起为闲置找到新去处。'}}</text></view><view class="public-stats"><view><text>{{member.itemCount}}</text><text>在架物品</text></view><view><text>{{member.exchangeCount}}</text><text>完成交换</text></view></view></view><view class="items-heading"><text class="cl-section-title">TA 的物品</text><text class="cl-tag">{{total}} 件在架</text></view><LoopSkeleton v-if="loading"/><view v-else-if="!items.length" class="cl-panel cl-empty"><LoopIcon name="box" :size="36" tone="primary"/><text>这位同学暂时没有在架物品</text></view><view v-else class="member-items"><ItemCard v-for="item in items" :key="item.id" :item="item"/></view><view v-if="total>12" class="member-pagination"><LoopButton class="cl-btn" :disabled="loading||page===1" @click="load(page-1)">上一页</LoopButton><text>{{page}} / {{Math.ceil(total/12)}}</text><LoopButton class="cl-btn" :disabled="loading||page*12>=total" @click="load(page+1)">下一页</LoopButton></view></template></LoopLayout></template>
<style scoped>
.member-cover{height:160px;border-radius:24px 24px 0 0;background:linear-gradient(120deg,var(--cl-primary-soft),var(--cl-blue-soft));overflow:hidden}.cover-pattern{display:flex;align-items:center;justify-content:flex-end;gap:28px;padding:20px 40px;color:var(--cl-primary);font-weight:700;letter-spacing:3px}.public-profile{position:relative;margin-top:-28px;display:flex;gap:24px;align-items:center;flex-wrap:wrap}.member-avatar{height:100px;width:100px;border-radius:28px;flex:none;border:5px solid var(--cl-surface);margin-top:-50px}.fallback{display:flex;align-items:center;justify-content:center;background:var(--cl-primary-soft);color:var(--cl-primary);font-size:44px;font-weight:700}.public-copy{flex:1;min-width:220px;display:flex;flex-direction:column;gap:14px}.member-bio{color:var(--cl-muted);font-size:14px;line-height:1.8;white-space:pre-wrap;overflow-wrap:anywhere}.public-stats{display:flex;gap:32px}.public-stats>view{display:flex;flex-direction:column;gap:8px;align-items:center;font-size:12px;color:var(--cl-muted)}.public-stats>view>text:first-child{font-size:28px;color:var(--cl-text);font-weight:700}.items-heading{display:flex;align-items:center;gap:16px;margin:32px 0 20px}.member-items{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.member-pagination{display:flex;justify-content:center;gap:20px;margin-top:24px}@media(max-width:950px){.member-items{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:600px){.member-items{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.public-profile{padding:20px;gap:16px}.member-cover{height:130px}.cover-pattern{padding:15px;font-size:12px;gap:10px}.member-avatar{width:72px;height:72px}.public-copy{min-width:180px}.public-copy .cl-title{font-size:23px}.public-stats{width:100%;justify-content:space-around;border-top:1px solid var(--cl-border);padding-top:18px}}
</style>
