<script setup>
import {reactive,ref,watch} from 'vue'
import LoopInput from './LoopInput.vue'
import LoopButton from './LoopButton.vue'
import LoopSheet from './LoopSheet.vue'
import http,{TOKEN_KEY,USER_KEY,clearSession} from '../common/http'
import {showAppModal} from '../common/modal'
import {onHide} from '@dcloudio/uni-app'
const props=defineProps({user:Object});const emit=defineEmits(['updated'])
const form=reactive({email:'',code:'',password:''}),busy=ref(false),error=ref(''),notice=ref(''),deleting=ref(false),deletePassword=ref('')
watch(()=>props.user,u=>{form.email=u?.email||'';form.code='';form.password='';deletePassword.value='';deleting.value=false},{immediate:true})
onHide(()=>{form.password='';deletePassword.value='';deleting.value=false})
const same=token=>token===uni.getStorageSync(TOKEN_KEY)
async function run(action){if(busy.value)return;const token=uni.getStorageSync(TOKEN_KEY);busy.value=true;error.value='';notice.value='';try{await action(token)}catch(e){if(same(token))error.value=e.message}finally{busy.value=false;form.password='';deletePassword.value=''}}
const send=()=>run(async token=>{await http.post('/api/account/email-code',{email:form.email},{silent:true});if(same(token))notice.value='验证码已发送，10 分钟内有效。'})
const bind=()=>run(async token=>{const u=await http.put('/api/account/email',{...form},{silent:true});if(same(token)){uni.setStorageSync(USER_KEY,u);emit('updated',u);notice.value='邮箱已验证，可以使用邮箱登录。'}})
const preference=()=>run(async token=>{await http.put('/api/account/mail-notifications',{enabled:!props.user.mailNotifications},{silent:true});if(same(token)){const u=await http.get('/api/auth/me');if(same(token)){uni.setStorageSync(USER_KEY,u);emit('updated',u);notice.value='账户安全邮件提醒设置已更新。'}}})
async function remove(){if(!deletePassword.value)return;const token=uni.getStorageSync(TOKEN_KEY);const choice=await showAppModal({title:'确认注销账号',content:'注销后无法恢复：个人资料会被清除，物品下架，动态隐藏；交换与治理记录保留。',confirmText:'确认注销',danger:true});if(!choice.confirm||!same(token))return;await run(async t=>{await http.delete('/api/account',{version:props.user.version,password:deletePassword.value,reason:'用户主动注销'},{silent:true});if(same(t)){clearSession();deleting.value=false;emit('updated',null);uni.switchTab({url:'/pages/profile/profile'})}})}
</script>
<template><view class="cl-panel security-panel"><text class="cl-section-title">邮箱与账号安全</text><text class="cl-hint">{{user.emailVerified?'已验证邮箱：'+user.email:user.legacyExchangeAccess?'老账号可以继续使用，绑定邮箱后支持邮箱登录与账户安全邮件提醒。':'验证邮箱后才能发布内容和参与交换。'}}</text><text class="cl-hint">邮件仅用于邮箱验证、密码修改或重置、登录地址变化等账户安全用途。商品审核、交换和评论等日常消息只在站内提醒。</text><form class="cl-form" @submit="bind"><LoopInput v-model="form.email" class="cl-input" aria-label="绑定邮箱" placeholder="邮箱地址" maxlength="254" :disabled="busy"/><LoopButton class="cl-btn" :disabled="busy||!form.email.trim()" @click="send">发送邮箱验证码</LoopButton><LoopInput v-model="form.code" class="cl-input" aria-label="绑定邮箱验证码" placeholder="6 位邮箱验证码" maxlength="6" :disabled="busy"/><LoopInput v-model="form.password" class="cl-input" aria-label="绑定邮箱的当前密码" placeholder="当前密码，用于确认本人操作" password maxlength="72" :disabled="busy"/><LoopButton class="cl-btn cl-btn--primary" form-type="submit" :disabled="busy||!form.password||!form.code">验证并绑定邮箱</LoopButton></form><LoopButton class="cl-btn" :disabled="busy||!user.emailVerified" :aria-pressed="user.mailNotifications" @click="preference">{{user.mailNotifications?'✓ 已开启账户安全邮件提醒 · 点击关闭':'开启账户安全邮件提醒'}}</LoopButton><text v-if="notice" class="cl-notice" role="status">{{notice}}</text><text v-if="error" class="cl-error" role="alert">{{error}}</text><LoopButton v-if="user.role!=='ADMIN'" class="cl-btn" :disabled="busy" @click="deleting=true">注销我的账号</LoopButton><LoopSheet v-model="deleting" dialog title="注销账号"><view class="cl-stack"><text class="cl-hint">请先完成或取消所有交换。注销后不能恢复账号，历史交换记录仍会保留。</text><LoopInput v-model="deletePassword" class="cl-input" aria-label="注销账号的当前密码" placeholder="输入当前密码" password maxlength="72"/><text v-if="error" class="cl-error">{{error}}</text><LoopButton class="cl-btn cl-btn--primary" :disabled="busy||!deletePassword" @click="remove">验证密码并注销</LoopButton></view></LoopSheet></view></template>
<style scoped>.security-panel{display:flex;flex-direction:column;gap:18px;margin-top:22px}.security-panel .cl-form{max-width:540px}.security-panel>.cl-btn{align-self:flex-start}</style>
