<script setup>
import ImageRotateButton from './ImageRotateButton.vue'
import MemberLink from './MemberLink.vue'
import {itemStatusLabel} from '../common/items'
import LoopSkeleton from './LoopSkeleton.vue'
import {ref,computed,watch,onMounted,onBeforeUnmount} from 'vue'
import {onShow,onHide} from '@dcloudio/uni-app'
import LoopButton from './LoopButton.vue'
import LoopInput from './LoopInput.vue'
import LoopSheet from './LoopSheet.vue'
import LoopIcon from './LoopIcon.vue'
import http,{TOKEN_KEY,USER_KEY,imageUrl} from '../common/http'
import {showAppModal} from '../common/modal'
const props=defineProps({postId:{type:Number,default:0},active:{type:Boolean,default:true}})
const rows=ref([]),page=ref(1),total=ref(0),loading=ref(false),error=ref(''),notice=ref(''),mine=ref(false),keyword=ref('')
const user=ref(null),body=ref(''),image=ref(''),itemId=ref(null),items=ref([]),uploading=ref(false),progress=ref(0),saving=ref(false)
const replyBody=ref(''),replies=ref([]),replyPage=ref(1),replyTotal=ref(0),replyLoading=ref(false),actionBusy=ref(false),reporting=ref(false),reportReason=ref('')
const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/20)))
const composerOpen=ref(false),editing=ref(null),replyOpen=ref(false),replyPostId=ref(0),reportPostId=ref(0)
function compose(post=null){if(!account()){login();return}editing.value=post;body.value=post?.body||'';image.value=post?.imageUrl||'';itemId.value=post?.itemId||null;error.value='';composerOpen.value=true}
function openReply(post){if(!account()){login();return}replyPostId.value=post.id;replyTarget.value=null;replyBody.value='';replyOpen.value=true}
function preview(url){uni.previewImage({urls:[imageUrl(url)]})}
const itemSheet=ref(false),itemSearch=ref(''),replyTarget=ref(null)
const selectedItem=computed(()=>items.value.find(item=>item.id===itemId.value))
const filteredItems=computed(()=>items.value.filter(item=>item.title.toLowerCase().includes(itemSearch.value.trim().toLowerCase())))
function selectItem(value){itemId.value=value;itemSheet.value=false}
function targetReply(row){if(!account()){login();return}replyTarget.value=row;replyRequest=null;replyPostId.value=props.postId;replyOpen.value=true}
function clearReplyTarget(){replyTarget.value=null;replyRequest=null}

let sequence=0,replySequence=0,alive=true,identity='',postRequest=null,replyRequest=null
const key=()=>Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,14)
const time=value=>new Date(/Z$/.test(value)?value:value+'Z').toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})
const login=()=>uni.navigateTo({url:`/pages/login/login?redirect=${props.postId?'community':'matches'}${props.postId?'&id='+props.postId:''}`})
const open=id=>uni.navigateTo({url:'/pages/community/community?id='+id})
const openItem=id=>uni.navigateTo({url:'/pages/detail/detail?id='+id})
function account(){const token=uni.getStorageSync(TOKEN_KEY)||'';if(identity!==token){composerOpen.value=false;replyOpen.value=false;reporting.value=false;editing.value=null;body.value='';image.value='';itemId.value=null;replyBody.value='';replyTarget.value=null;itemSheet.value=false;postRequest=null;replyRequest=null;items.value=[];mine.value=false;notice.value='';rows.value=[];replies.value=[];identity=token}user.value=token?uni.getStorageSync(USER_KEY):null;return token}
const current=token=>alive&&token===(uni.getStorageSync(TOKEN_KEY)||'')
async function load(){
 if(!props.active)return
 alive=true;const token=account(),attempt=++sequence;loading.value=true;error.value=''
 try{const data=props.postId?await http.get('/api/community/posts/'+props.postId,{}, {silent:true}):await http.get('/api/community/posts',{page:page.value,size:20,mine:mine.value,keyword:keyword.value.trim()},{silent:true});if(!current(token)||attempt!==sequence)return;rows.value=props.postId?[data]:data.records;total.value=props.postId?1:data.total;if(props.postId)await loadReplies()}
 catch(e){if(attempt===sequence&&current(token))error.value=e.message;else if(e.status===401&&attempt===sequence){account();error.value='请登录后继续'}}
 finally{if(attempt===sequence)loading.value=false}
 if(token){try{const own=await http.get('/api/items/mine',{page:1,size:100},{silent:true});if(current(token)&&attempt===sequence)items.value=own.records.filter(i=>['AVAILABLE','RESERVED','EXCHANGED'].includes(i.status))}catch{}}
}
async function loadReplies(){const token=account(),attempt=++replySequence;replyLoading.value=true;try{const data=await http.get(`/api/community/posts/${props.postId}/replies`,{page:replyPage.value,size:20},{silent:true});if(current(token)&&attempt===replySequence){replies.value=data.records;replyTotal.value=data.total}}catch(e){if(current(token)&&attempt===replySequence)error.value=e.message}finally{if(attempt===replySequence)replyLoading.value=false}}
async function send(){
 const token=account();if(!token){login();return}if(saving.value||uploading.value||!body.value.trim())return
 const fields={body:body.value.trim(),itemId:itemId.value,imageUrl:image.value||null};if(!postRequest||JSON.stringify(postRequest.fields)!==JSON.stringify(fields))postRequest={fields,requestKey:key()}
 saving.value=true;error.value=''
 try{if(editing.value)await http.patch('/api/community/posts/'+editing.value.id,{...fields,version:editing.value.version},{silent:true});else await http.post('/api/community/posts',{...postRequest.fields,requestKey:postRequest.requestKey},{silent:true});if(!current(token))return;body.value='';image.value='';itemId.value=null;postRequest=null;page.value=1;mine.value=false;notice.value=editing.value?'动态已保存':'动态已发布';composerOpen.value=false;editing.value=null;await load()}
 catch(e){if(current(token))error.value=e.message}finally{saving.value=false}
}
function pickImage(){const token=account();if(!token){login();return}if(uploading.value||saving.value)return;uni.chooseImage({count:1,sizeType:['original'],success:async result=>{if(!current(token))return;uploading.value=true;progress.value=0;error.value='';try{const data=await http.upload(result.tempFilePaths[0],{silent:true,onProgress:value=>{if(current(token))progress.value=value}});if(current(token)){image.value=data.url;notice.value='图片上传成功'}}catch(e){if(current(token))error.value=e.message}finally{uploading.value=false}}})}
async function react(post){const token=account();if(!token){login();return}if(actionBusy.value)return;actionBusy.value=true;error.value='';try{await http[post.liked?'delete':'put'](`/api/community/posts/${post.id}/like`,{}, {silent:true});if(current(token)){post.likes+=post.liked?-1:1;post.liked=!post.liked}}catch(e){if(current(token))error.value=e.message}finally{actionBusy.value=false}}
async function withdraw(post){const token=account();if(actionBusy.value)return;const choice=await showAppModal({title:'撤回动态',content:'撤回后，其他同学将无法查看这条动态。',confirmText:'撤回'});if(!choice.confirm||!current(token))return;actionBusy.value=true;try{await http.delete('/api/community/posts/'+post.id,{version:post.version},{silent:true});if(current(token)){notice.value='动态已撤回';if(props.postId){rows.value=[];replies.value=[]}else await load()}}catch(e){if(current(token))error.value=e.message}finally{actionBusy.value=false}}
async function reply(){const token=account();if(!token){login();return}if(saving.value||!replyBody.value.trim())return;const text=replyBody.value.trim();if(replyRequest?.body!==text||replyRequest?.parentReplyId!==(replyTarget.value?.id||null))replyRequest={body:text,parentReplyId:replyTarget.value?.id||null,requestKey:key()};saving.value=true;error.value='';try{await http.post(`/api/community/posts/${replyPostId.value||props.postId}/replies`,replyRequest,{silent:true});if(current(token)){replyBody.value='';replyTarget.value=null;replyRequest=null;notice.value='回复已发送';replyOpen.value=false;replyPage.value=Math.max(1,Math.ceil((replyTotal.value+1)/20));await load()}}catch(e){if(current(token))error.value=e.message}finally{saving.value=false}}
async function removeReply(row){const token=account();if(actionBusy.value)return;const choice=await showAppModal({title:'撤回回复',content:'确定撤回这条回复吗？',confirmText:'撤回'});if(!choice.confirm||!current(token))return;actionBusy.value=true;try{await http.delete(`/api/community/posts/${props.postId}/replies/${row.id}`,{}, {silent:true});if(current(token))await load()}catch(e){if(current(token))error.value=e.message}finally{actionBusy.value=false}}
function startReport(post){reportPostId.value=post.id;if(!account()){login();return}reporting.value=!reporting.value;reportReason.value=''}
async function report(){const token=account();if(!reportReason.value.trim()||actionBusy.value)return;actionBusy.value=true;try{await http.post(`/api/community/posts/${reportPostId.value}/reports`,{reason:reportReason.value.trim()},{silent:true});if(current(token)){reporting.value=false;notice.value='举报已提交，管理员会查看处理'}}catch(e){if(current(token))error.value=e.message}finally{actionBusy.value=false}}
function filterMine(){if(!account()){login();return}mine.value=!mine.value;page.value=1;load()}
function changePage(delta){page.value+=delta;load()}
function changeReplies(delta){replyPage.value+=delta;loadReplies()}
onMounted(load);onShow(load);watch(()=>props.active,value=>{if(value)load();else sequence++});onHide(()=>{alive=false;sequence++;replySequence++});onBeforeUnmount(()=>{alive=false;sequence++;replySequence++})
</script>
<template>
 <view class="community-shell" :class="{detail:postId}"><view class="community-feed">
  <view v-if="!postId" class="cl-panel composer">
   <view class="community-heading"><text class="cl-section-title">校园动态</text><text class="cl-hint">晒晒闲置，说说需要，认识一起交换的同学。</text></view>
   <LoopButton v-if="user" class="cl-btn cl-btn--primary" @click="compose()"><LoopIcon name="plus" tone="white"/> 写一条动态</LoopButton>
   <view v-if="!user" class="guest-prompt"><text>登录后可以发布动态、回复和点赞。</text><LoopButton class="cl-btn cl-btn--primary" @click="login">登录参与</LoopButton></view>
  </view>
  <view v-if="!postId" class="feed-toolbar"><LoopButton class="cl-btn" :class="{'cl-btn--primary':mine}" @click="filterMine">{{mine?'我的动态':'全部动态'}}</LoopButton><LoopInput v-model="keyword" class="cl-input" placeholder="搜索校园动态" aria-label="搜索校园动态" :maxlength="100" @confirm="page=1;load()"/><LoopButton class="cl-btn" :disabled="loading" @click="page=1;load()">搜索</LoopButton></view>
  <text v-if="notice" class="cl-notice feed-message" role="status">{{notice}}</text><view v-if="error" class="cl-notice feed-message" role="alert"><text class="cl-error">{{error}}</text><LoopButton class="cl-btn" @click="load">重新加载</LoopButton></view>
  <LoopSkeleton v-if="loading" />
  <view v-else-if="!rows.length&&!error" class="cl-panel cl-empty"><text>{{postId?'这条动态已撤回':'还没有动态，来分享第一件好物吧'}}</text></view>
  <view v-for="post in rows" :key="post.id" class="cl-panel feed-post">
   <view class="post-author"><MemberLink :id="post.authorId" :name="post.authorName" :avatar="post.avatarUrl" :show-name="false" :size="40"/><view><text class="cl-field-title">{{post.authorName}}</text><text class="cl-hint">{{time(post.createdAt)}}{{post.status==='HIDDEN'?' · 已被隐藏':''}}</text></view><LoopButton v-if="post.authorId===user?.id" class="cl-btn cl-btn--quiet" @click="compose(post)">编辑</LoopButton><LoopButton v-if="post.authorId===user?.id" class="cl-btn cl-btn--quiet" :disabled="actionBusy" @click="withdraw(post)">撤回</LoopButton></view>
   <text class="post-body">{{post.body}}</text><image v-if="post.imageUrl" class="post-image" :src="imageUrl(post.imageUrl)" mode="widthFix" @click="preview(post.imageUrl)"/>
   <LoopButton v-if="post.itemId&&post.itemTitle" class="attached-item" @click="openItem(post.itemId)"><image :src="imageUrl(post.itemImage,post.itemTitle)" mode="aspectFill"/><view><text class="cl-tag" :class="{'cl-tag--pink':post.itemStatus==='EXCHANGED'}">{{post.itemStatus==='AVAILABLE'?'未交换 · 可交换':itemStatusLabel(post.itemStatus)}}</text><text class="cl-field-title">{{post.itemTitle}}</text></view><text>查看 ›</text></LoopButton>
   <text v-else-if="post.itemId" class="cl-hint">关联物品暂不可见</text>
   <view v-if="!postId&&post.previewReplies?.length" class="comment-preview"><LoopButton v-for="comment in post.previewReplies" :key="comment.id" class="preview-comment" @click="open(post.id)"><text class="preview-author">{{comment.authorName}}：</text><text>{{comment.body}}</text></LoopButton><LoopButton class="preview-more" @click="open(post.id)">查看全部 {{post.replies}} 条评论 ›</LoopButton></view>
   <view class="post-actions"><LoopButton class="cl-btn" :class="{'cl-btn--primary':post.liked}" :aria-pressed="post.liked" :disabled="actionBusy||post.status!=='PUBLISHED'" @click="react(post)">{{post.liked?'♥ 已赞':'♡ 赞'}} {{post.likes}}</LoopButton><LoopButton class="cl-btn" @click="openReply(post)">回复 {{post.replies}}</LoopButton><LoopButton v-if="post.authorId!==user?.id" class="cl-btn cl-btn--quiet" @click="startReport(post)">举报</LoopButton><LoopButton v-if="!postId" class="cl-btn cl-btn--quiet" @click="open(post.id)">查看讨论 ›</LoopButton></view>
  </view>
  <view v-if="postId&&rows.length" class="cl-panel replies">
   <text class="cl-section-title">回复 · {{replyTotal}}</text>
   <LoopButton v-if="rows[0].status==='PUBLISHED'" class="cl-btn cl-btn--primary" @click="openReply(rows[0])">写评论</LoopButton>
   <LoopSkeleton v-if="replyLoading" /><view v-else-if="!replies.length" class="cl-empty">还没有回复</view>
   <view v-for="row in replies" :key="row.id" class="reply-row"><view class="post-author"><MemberLink :id="row.authorId" :name="row.authorName" :avatar="row.avatarUrl" :show-name="false" :size="40"/><view><text class="cl-field-title">{{row.authorName}}</text><text class="cl-hint">{{time(row.createdAt)}}</text></view><LoopButton v-if="row.authorId===user?.id" class="cl-btn cl-btn--quiet" :disabled="actionBusy" @click="removeReply(row)">撤回</LoopButton></view><text v-if="row.parentReplyId" class="reply-context">回复 {{row.replyToName||'已撤回的评论'}}</text><text class="post-body">{{row.body}}</text><LoopButton v-if="rows[0].status==='PUBLISHED'" class="cl-btn cl-btn--quiet reply-target-button" :disabled="saving" @click="targetReply(row)">回复 {{row.authorName}}</LoopButton></view>
   <view v-if="replyTotal>20" class="feed-pagination"><LoopButton class="cl-btn" :disabled="replyLoading||replyPage<=1" @click="changeReplies(-1)">上一页</LoopButton><text>{{replyPage}}</text><LoopButton class="cl-btn" :disabled="replyLoading||replyPage*20>=replyTotal" @click="changeReplies(1)">下一页</LoopButton></view>
  </view>
  <view v-if="!postId&&total>0" class="feed-pagination"><LoopButton class="cl-btn" :disabled="loading||page<=1" @click="changePage(-1)">上一页</LoopButton><text>第 {{page}} / {{totalPages}} 页 · {{total}} 条动态</text><LoopButton class="cl-btn" :disabled="loading||page>=totalPages" @click="changePage(1)">下一页</LoopButton></view>
  <LoopSheet v-model="composerOpen" dialog :title="editing?'编辑动态':'发布校园动态'">   <view class="composer"><LoopInput v-model="body" multiline class="cl-textarea" aria-label="动态内容" placeholder="最近有什么想出手，或想找到的好物？" :maxlength="2000" :disabled="saving"/><image v-if="image" class="attached-image" :src="imageUrl(image)" mode="aspectFit"/><ImageRotateButton v-if="image" :url="image" :disabled="uploading||saving" @busy="uploading=$event" @rotated="image=$event"/><view class="composer-tools"><LoopButton class="cl-btn" :disabled="saving||uploading" @click="pickImage">{{uploading?`上传中 ${progress}%`:'添加图片'}}</LoopButton><LoopButton v-if="image" class="cl-btn" :disabled="saving||uploading" @click="image=''">移除图片</LoopButton><LoopButton class="cl-btn attach-trigger" :disabled="saving" aria-label="关联我的物品" @click="itemSheet=true"><LoopIcon name="box" tone="primary"/><image v-if="selectedItem" :src="imageUrl(selectedItem.imageUrl,selectedItem.title)" mode="aspectFill"/><text>{{selectedItem?.title||'关联我的物品'}}</text><LoopIcon name="plus" :size="16"/></LoopButton><LoopButton class="cl-btn cl-btn--primary" :disabled="saving||uploading||!body.trim()" :loading="saving" @click="send">{{editing?'保存修改':'发布动态'}}</LoopButton></view></view><text v-if="error" class="cl-error" role="alert">{{error}}</text></LoopSheet>
  <LoopSheet v-model="replyOpen" dialog :title="replyTarget?'回复 '+replyTarget.authorName:'写评论'">
   <view  class="reply-composer"><view v-if="replyTarget" class="reply-target"><text>回复 {{replyTarget.authorName}}</text><LoopButton class="cl-btn cl-btn--quiet" aria-label="取消回复对象" @click="clearReplyTarget">取消</LoopButton></view><LoopInput v-if="user" v-model="replyBody" multiline class="cl-textarea" aria-label="回复内容" :placeholder="replyTarget?`回复 ${replyTarget.authorName}…`:'聊聊你的想法，或询问物品细节…'" :maxlength="1000" :disabled="saving"/><LoopButton class="cl-btn cl-btn--primary" :disabled="saving||(!!user&&!replyBody.trim())" @click="reply">{{user?'发送回复':'登录后回复'}}</LoopButton></view><text v-if="error" class="cl-error" role="alert">{{error}}</text></LoopSheet>
  <LoopSheet v-model="reporting" dialog title="举报动态">   <view  class="report-box"><LoopInput v-model="reportReason" multiline class="cl-textarea" aria-label="举报原因" placeholder="请说明需要管理员查看的内容" :maxlength="500"/><LoopButton class="cl-btn cl-btn--primary" :disabled="actionBusy||!reportReason.trim()" @click="report">提交举报</LoopButton></view><text v-if="error" class="cl-error" role="alert">{{error}}</text></LoopSheet>
  <LoopSheet v-model="itemSheet" title="关联我的物品"><view class="item-selector"><text class="cl-hint">选一件已公开的物品，让同学从动态直接查看详情。</text><LoopInput v-model="itemSearch" class="cl-input" aria-label="搜索我的物品" placeholder="搜索物品名称"/><LoopButton class="cl-btn" @click="selectItem(null)">不关联物品</LoopButton><LoopButton v-for="item in filteredItems" :key="item.id" class="item-option" :class="{selected:itemId===item.id}" :aria-pressed="itemId===item.id" @click="selectItem(item.id)"><image :src="imageUrl(item.imageUrl,item.title)" mode="aspectFill"/><view><text class="cl-field-title">{{item.title}}</text><text class="cl-hint">{{item.categoryName}} · {{item.status==='AVAILABLE'?'可交换':item.status==='RESERVED'?'交换中':'已交换'}}</text></view><LoopIcon v-if="itemId===item.id" name="check" tone="primary"/></LoopButton><text v-if="!filteredItems.length" class="cl-empty">{{items.length?'没有找到这件物品':'还没有可关联的公开物品'}}</text></view></LoopSheet>
 </view><view v-if="!postId" class="community-aside"><view class="aside-card"><image src="/static/campus-courtyard.png" mode="aspectFill"/><text class="cl-section-title">校园交换小站</text><text class="cl-hint">晒晒好物，聊聊想法。在这里遇见一起交换的同学。</text></view><view class="cl-panel topic-card"><text class="cl-field-title"><LoopIcon name="sun" tone="primary" :size="20"/> 聊点什么</text><LoopButton v-for="topic in ['这学期想换到什么','晒晒我的宿舍好物','读完一本书，传给下一位']" :key="topic" class="topic-button" :disabled="saving" @click="composerOpen=true;body=body?body+' #'+topic:'#'+topic+' '"># {{topic}} <text>＋</text></LoopButton><text class="cl-hint">点选话题，加入你的动态草稿</text></view><view class="aside-tips"><LoopIcon name="heart" tone="primary" :size="18"/><text>友好交流，如实介绍物品；确认交换后，再约定交接地点。</text></view></view></view>
</template>
<style scoped>
.community-feed{max-width:800px;margin:0 auto;display:flex;flex-direction:column;gap:18px}.composer,.community-heading,.replies{display:flex;flex-direction:column;gap:16px}.composer .cl-textarea,.reply-composer .cl-textarea{min-height:110px;width:100%}.composer-tools,.feed-toolbar,.post-actions,.guest-prompt{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.composer-tools>.cl-btn--primary{margin-left:auto}.composer-tools .cl-picker{max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.feed-toolbar .cl-input{flex:1;min-width:140px}.feed-message{display:block;margin:0}.feed-post{display:flex;flex-direction:column;gap:18px}.post-author{display:flex;align-items:center;gap:12px}.post-author>view{flex:1;min-width:0}.post-author .cl-hint{display:block;margin-top:3px}.post-avatar{height:40px;width:40px;border-radius:50%}.post-body{display:block;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8}.post-image,.attached-image{width:100%;max-width:100%;height:280px;background:var(--cl-surface-soft);border-radius:14px}.attached-image{height:150px}.attached-item{display:flex;align-items:center;gap:14px;padding:12px;background:var(--cl-surface-soft);border:1px solid var(--cl-border);border-radius:14px;text-align:left;color:var(--cl-text)}.attached-item image{height:62px;width:62px;border-radius:10px;flex-shrink:0}.attached-item>view{flex:1;min-width:0}.attached-item .cl-hint,.attached-item .cl-field-title{display:block}.post-actions{border-top:1px solid var(--cl-border);padding-top:14px}.post-actions>.cl-btn--quiet:last-child{margin-left:auto}.reply-composer,.report-box{display:flex;flex-direction:column;gap:12px}.reply-row{border-top:1px solid var(--cl-border);padding-top:18px}.reply-row .post-body{padding:12px 0 0 52px}.feed-pagination{display:flex;align-items:center;justify-content:center;gap:16px}@media(max-width:600px){.composer-tools>.cl-btn--primary{width:100%;margin-left:0}.composer-tools .cl-picker{max-width:190px}.feed-post,.composer,.replies{padding:20px}.post-image{height:220px}.feed-toolbar .cl-input{order:3;flex-basis:100%}.post-actions{gap:6px}.post-actions .cl-btn{font-size:12px;padding:8px 10px}.reply-row .post-body{padding-left:0}}

.attach-trigger{max-width:100%;min-width:200px}.attach-trigger>text{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:220px}.attach-trigger image{width:32px;height:32px;border-radius:6px}.item-selector{display:flex;flex-direction:column;gap:16px}.item-option{width:100%;display:flex;align-items:center;gap:14px;padding:14px;background:var(--cl-surface);border:1px solid var(--cl-border);border-radius:14px;text-align:left;color:var(--cl-text)}.item-option.selected{border-color:var(--cl-primary);background:var(--cl-primary-soft)}.item-option image{width:64px;height:64px;border-radius:10px;flex:none}.item-option>view{display:flex;flex-direction:column;gap:6px;flex:1;min-width:0}.comment-preview{padding:14px 18px;background:var(--cl-surface-soft);border-radius:14px;display:flex;flex-direction:column;gap:8px}.preview-comment,.preview-more{background:transparent;color:var(--cl-text);font-size:13px;text-align:left;padding:4px 0;width:100%;line-height:1.7;white-space:normal;overflow-wrap:anywhere}.preview-comment{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden}.preview-author{font-weight:700;color:var(--cl-blue)}.preview-more{color:var(--cl-primary);font-weight:600}.reply-target{display:flex;justify-content:space-between;align-items:center;padding:8px 14px;background:var(--cl-primary-soft);border-radius:12px;color:var(--cl-primary)}.reply-context{display:block;margin-top:14px;color:var(--cl-blue);font-size:12px}.reply-target-button{margin-top:8px}.feed-pagination{padding:16px;border:1px solid var(--cl-border);background:var(--cl-surface);border-radius:16px;flex-wrap:wrap;font-size:13px}
.community-shell{display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:24px;align-items:start;max-width:1120px;margin:0 auto}.community-shell.detail{display:block;max-width:800px}.community-feed{width:100%;min-width:0}.community-aside{position:sticky;top:20px;display:flex;flex-direction:column;gap:18px}.aside-card{overflow:hidden;border:1px solid var(--cl-border);border-radius:20px;background:var(--cl-surface);padding-bottom:20px}.aside-card image{width:100%;height:140px}.aside-card>.cl-section-title,.aside-card>.cl-hint{display:block;margin:16px 18px 0}.aside-card>.cl-section-title{font-size:18px}.topic-card{display:flex;flex-direction:column;gap:12px;padding:20px}.topic-button{display:flex;justify-content:space-between;text-align:left;gap:8px;padding:10px 0;background:transparent;color:var(--cl-blue);font-size:12px;line-height:1.6}.aside-tips{display:flex;gap:10px;padding:0 12px;font-size:12px;color:var(--cl-muted);line-height:1.8}@media(max-width:950px){.community-shell{grid-template-columns:1fr}.community-aside{display:none}}
.post-image{height:auto;max-height:none;cursor:zoom-in}.post-author{flex-wrap:wrap}.post-author>view{min-width:110px}
</style>
